services:
#nginx
# To enable the nginx ingress controller in a Kubernetes cluster, you need to install it.
  web: 
      image: nginx:latest
      ports: 
      - "80:80"
      volumes: 
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  app:
      build:
           dockerfile: ./php/Dockerfile
      volumes:
          - ./app:/app
#php
#mysql
#redis
